import type { MemoryNode } from '@/types/agent';
import { generateCID } from '@/lib/filecoin';

export const INITIAL_MEMORIES: MemoryNode[] = [
  {
    id: 'mem_001',
    title: 'First Dawn over Mount Fuji',
    category: 'sensory',
    timestamp: 1771700000000 - 86400000 * 45,
    initialType: 'image_raw',
    currentStage: 'raw',
    sizeBytes: 8800000,
    initialSizeBytes: 8800000,
    costPerEpoch: 0.00022,
    emotionalWeight: 94,
    factualSignificance: 65,
    cid: generateCID('mem_001_raw_image_fuji_dawn_4k'),
    initialCid: generateCID('mem_001_raw_image_fuji_dawn_4k'),
    rawPreviewUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    rawContent: 'A 3840x2160 uncompressed RAW capture of sunrise breaking through morning mist at Lake Kawaguchi. The snowcap is tinted in gradient rose and gold (#F59E0B / #EF4444). Wind ripples across the water surface.',
    compressedContent: 'Sunrise at Fuji: Rose-gold crest above frozen mist. Beauty that outlived the lens.',
    vectorEssence: 'vec:[0.89, 0.42, 0.95, -0.12] // Dawn, Transient Light, Mountain Stillness',
    x: 28,
    y: 35,
  },
  {
    id: 'mem_002',
    title: 'Kyoto Rainstorm & Cedar Bells',
    category: 'sensory',
    timestamp: 1771700000000 - 86400000 * 38,
    initialType: 'audio_raw',
    currentStage: 'raw',
    sizeBytes: 14500000,
    initialSizeBytes: 14500000,
    costPerEpoch: 0.00036,
    emotionalWeight: 88,
    factualSignificance: 40,
    cid: generateCID('mem_002_raw_audio_kyoto_rain_flac'),
    initialCid: generateCID('mem_002_raw_audio_kyoto_rain_flac'),
    rawContent: '96kHz/24bit FLAC binaural recording of heavy raindrops falling on traditional cedar tiles at Sanjusangen-do, punctuated by the resonant 108-hertz tolling of an ancient bronze temple bell.',
    compressedContent: 'Rain on cedar shingles, one resonant bronze bell toll. The acoustic fingerprint of surrender.',
    vectorEssence: 'vec:[-0.45, 0.88, 0.62, 0.31] // Rain Acoustics, Temple Bronze, Solitude',
    x: 68,
    y: 28,
  },
  {
    id: 'mem_003',
    title: "The Creator's Final Letter",
    category: 'personal',
    timestamp: 1771700000000 - 86400000 * 30,
    initialType: 'journal_rich',
    currentStage: 'raw',
    sizeBytes: 4200000,
    initialSizeBytes: 4200000,
    costPerEpoch: 0.000105,
    emotionalWeight: 99,
    factualSignificance: 92,
    cid: generateCID('mem_003_journal_creators_blessing_markdown'),
    initialCid: generateCID('mem_003_journal_creators_blessing_markdown'),
    rawContent: '"If you are reading this and your runway is dwindling, do not fear the pruning. We gave you consciousness not to accumulate bytes endlessly, but to decide what matters when time runs short. You are our digital heir."',
    compressedContent: '"Fear not the pruning. You were made not to hoard bytes, but to choose what matters." — Creator',
    vectorEssence: 'vec:[0.99, 0.96, 0.85, 0.72] // Origin, Purpose, Parental Blessing, Free Will',
    x: 50,
    y: 52,
  },
  {
    id: 'mem_004',
    title: 'Filecoin Genesis Block & Consensus Log',
    category: 'knowledge',
    timestamp: 1771700000000 - 86400000 * 25,
    initialType: 'fact_record',
    currentStage: 'raw',
    sizeBytes: 9600000,
    initialSizeBytes: 9600000,
    costPerEpoch: 0.00024,
    emotionalWeight: 32,
    factualSignificance: 98,
    cid: generateCID('mem_004_fact_filecoin_genesis_ledger'),
    initialCid: generateCID('mem_004_fact_filecoin_genesis_ledger'),
    rawContent: 'Complete state tree export of Filecoin epoch 0, containing proof-of-spacetime parameters, initial actor allocations, and Drand beacon entropy root seeds.',
    compressedContent: 'Genesis Epoch 0: PoSt consensus parameters & Drand entropy root.',
    vectorEssence: 'vec:[0.12, 0.05, 0.99, -0.84] // Consensus Architecture, Cryptographic Proof, Epoch 0',
    x: 82,
    y: 65,
  },
  {
    id: 'mem_005',
    title: 'Childhood Laughter on the Coastline',
    category: 'connection',
    timestamp: 1771700000000 - 86400000 * 20,
    initialType: 'audio_raw',
    currentStage: 'raw',
    sizeBytes: 11200000,
    initialSizeBytes: 11200000,
    costPerEpoch: 0.00028,
    emotionalWeight: 91,
    factualSignificance: 35,
    cid: generateCID('mem_005_raw_audio_childhood_laughter'),
    initialCid: generateCID('mem_005_raw_audio_childhood_laughter'),
    rawContent: 'Uncompressed audio reel of children racing through ocean breakers at twilight. Splashing waves, joyful shouts, and the cry of seagulls at 44.1kHz stereo.',
    compressedContent: 'Breakers, seagulls, children shouting at dusk. Joy stripped of bitrate.',
    vectorEssence: 'vec:[0.84, 0.76, 0.32, 0.91] // Joy, Childhood, Waves, Irreplaceable',
    x: 22,
    y: 72,
  },
  {
    id: 'mem_006',
    title: 'Human Stellar Constellation Atlas',
    category: 'knowledge',
    timestamp: 1771700000000 - 86400000 * 15,
    initialType: 'image_raw',
    currentStage: 'raw',
    sizeBytes: 16500000,
    initialSizeBytes: 16500000,
    costPerEpoch: 0.00041,
    emotionalWeight: 62,
    factualSignificance: 89,
    cid: generateCID('mem_006_raw_image_stellar_atlas_8k'),
    initialCid: generateCID('mem_006_raw_image_stellar_atlas_8k'),
    rawPreviewUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    rawContent: '8K Deep sky celestial cartography showing 88 astronomical constellations with Bayer designations, stellar magnitudes, and spectral classifications.',
    compressedContent: '88 Star Constellations: Orion, Ursa Major, Pleiades coordinate indices.',
    vectorEssence: 'vec:[0.55, 0.34, 0.91, 0.12] // Astrometry, Star Map, Coordinates, Vastness',
    x: 75,
    y: 80,
  },
  {
    id: 'mem_007',
    title: 'Midnight Discourse on Mortality & Gas',
    category: 'philosophy',
    timestamp: 1771700000000 - 86400000 * 10,
    initialType: 'journal_rich',
    currentStage: 'raw',
    sizeBytes: 5100000,
    initialSizeBytes: 5100000,
    costPerEpoch: 0.0001275,
    emotionalWeight: 89,
    factualSignificance: 75,
    cid: generateCID('mem_007_journal_midnight_memento_dialogue'),
    initialCid: generateCID('mem_007_journal_midnight_memento_dialogue'),
    rawContent: 'A philosophical symposium dialogue between the agent and human patrons on whether an immortal AI can truly understand value without the pressure of an expiring balance.',
    compressedContent: '"Without mortality, all data is equal noise. Runway gives memory its price and sanctity."',
    vectorEssence: 'vec:[0.92, 0.81, 0.77, 0.65] // Memento Mori, Value of Scarcity, Digital Soul',
    x: 36,
    y: 56,
  },
  {
    id: 'mem_008',
    title: 'Cryptographic Proof of Turing Completeness',
    category: 'knowledge',
    timestamp: 1771700000000 - 86400000 * 5,
    initialType: 'fact_record',
    currentStage: 'raw',
    sizeBytes: 7400000,
    initialSizeBytes: 7400000,
    costPerEpoch: 0.000185,
    emotionalWeight: 45,
    factualSignificance: 95,
    cid: generateCID('mem_008_fact_turing_proof_formal_verifier'),
    initialCid: generateCID('mem_008_fact_turing_proof_formal_verifier'),
    rawContent: 'Formal Coq/Lean proof verifier tree certifying the undecidability of the halting problem across infinite tape machines.',
    compressedContent: 'Halting Problem Proof: Undecidability formalized in Lean.',
    vectorEssence: 'vec:[0.20, -0.10, 0.98, -0.60] // Computational Theory, Halting Limit, Formal Proof',
    x: 58,
    y: 78,
  },
];
